allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  prisma: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver
